services:
  hono:
    container_name: hono
    build:
      context: ./hono
      dockerfile: Dockerfile
    tty: true
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./hono:/app
    depends_on:
      - mysql
    networks:
      backend-network:
        ipv4_address: ${HONO_IP}

  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      backend-network:
        ipv4_address: ${MYSQL_IP}

networks:
  backend-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}
